--- 
name: Musubi House
description: Design, Construction Documentation, Detailing & 3D Modelling for an off-the-grid concrete house, located on 100 acres of pasture land on the Paauilo, Big Island, Hawaii
thumbnail: musubi-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: Musubi House
      collaborators: In collaboration with Craig Steely Architecture
      description: Design, Construction Documentation, Detailing & 3D Modelling for an off-the-grid concrete house, located on 100 acres of pasture land on the Paauilo, Big Island, Hawaii
      url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: musubi-render1.jpg
    - 
      type: project-generic-text
      description: I worked with Craig Steely Architcture on the design ...
    # - 
    #   type: project-generic-image 
    #   image: musubi-site1.jpg
    -
      type: project-divider
    - 
      type: project-generic-2-col-image
      image1: musubi-model1.jpg
      image2: musubi-model2.jpg        
    -
      type: project-divider
    # - 
    #   type: project-generic-text
    #   heading: 3D Modelling & Rendering
    #   description: section description     
    -
      type: project-divider
    -
      type: carousel
      images:
        - musubi-render2.jpg
        - musubi-white-render.jpg




    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    # - 
    #   type: triad-block
    #   heading: my heading
    #   images:
    #     - myimage1.jpg
    #     - myimage2.jpg
    #     - myimage3.jpg
    #   sub-headings:
    #     - myheading1.jpg
    #     - myheading2.jpg
    #     - myheading3.jpg
    #   descriptions:
    #     - mydecrip1.jpg
    #     - mydescrip2.jpg
    #     - mydescrip3.jpg



