--- 
name: SFMOMA Living Wall
description: Systems engineering & Project management for a 3-story, $190M living wall installation at SFMOMA
thumbnail: sfmoma-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: SFMOMA Living Wall
      collaborators: In collaboration with Hyphae Design Lab, Habitat Horticulture, Snohetta & SFMOMA
      description: Systems engineering, Construction detailling & Project management for a 3-story, $190M living wall installation at SFMOMA
      url: www.sfmoma.org/watch/the-living-wall
    - 
      type: project-generic-image 
      image: sfmoma_living_wall_overhead.jpg
    - 
      type: project-generic-text
      description: section description   
    -
      type: project-divider
    - 
      type: project-generic-image 
      image: sfmoma_living_wall2.jpg
    -
      type: project-divider
    - 
      type: project-generic-2-col-image
      image1: sfmoma-system.jpg
      image2: sfmoma-planting.jpg          
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    # - 
    #   type: triad-block
    #   heading: my heading
    #   images:
    #     - myimage1.jpg
    #     - myimage2.jpg
    #     - myimage3.jpg
    #   sub-headings:
    #     - myheading1.jpg
    #     - myheading2.jpg
    #     - myheading3.jpg
    #   descriptions:
    #     - mydecrip1.jpg
    #     - mydescrip2.jpg
    #     - mydescrip3.jpg



