--- 
name: Tenderloin Public Toilet Project / Pplanter
description: User Research, Experience Design, Industrial design & Systems engineering for a ecologically friendly street toilet prototype
thumbnail: pplanter-thumb.jpg
wip: false
featured: false
date: Jun 2012 - May 2014 //
meta: Industrial Design / R & D / UX research
blocks: 
    - 
      type: project-header
      date: Jun 2012 - May 2014 //
      heading: Tenderloin Public Toilet Project / Pplanter
      tags:  R&D / UX Research / UX Design / Industrial Design / Systems Design
      collaborators: In collaboration with Hyphae Design Lab
      description: User Research, Experience Design, Industrial design & Systems engineering for a ecologically friendly street toilet prototype
      # url: pplanter.org
    - 
      type: project-generic-image 
      image: pplanter-main.jpg
    - 
      type: project-generic-text
      description: The PPlanter, a modular street toilet that uses biofiltration to process waste collected, is a project I've worked on in various respects over the past 3 years. It has undergone 3 official iterations and been installed on a trial basis in San Francisco to collect data on usage and to test system components.
    - 
      type: project-generic-text
      heading: More coming soon ...   
    # -
    #   type: project-design-goals
    #   heading: Design Goals
    #   items:
    #     -
    #       image: pplanter-question.svg
    #       sub-heading: Refine and communicate product value proposition
    #     -
    #       image: pplanter-brand.svg
    #       sub-heading: Establish clear brand identity that resonates with target users
    #     -
    #       image: pplanter-user.svg
    #       sub-heading: Build an engaged audience           
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description


