--- 
name: Material Intelligence
description: A study into dynamic surface generation through component propagation 
thumbnail: chevron-thumb.gif
blocks: 
    - 
      type: project-header
      heading: Material Intelligence
      collaborators: For Prof Jordi Truco & Lec.Kat Park -- In collaboration with Ash Low & Win Mixter
      description: A study into dynamic surface generation through component propagation
      # url: www.xyz.com
    - 
      type: project-generic-image 
      image: chevron-main.jpg
    -
      type: project-divider  
    - 
      type: project-generic-text
      # heading: Final Thoughts
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si
    # -
    #   type: project-divider
    - 
      type: project-generic-image 
      image: chevron-comp2.png             
    - 
      type: project-generic-text
      heading: The Component - Chevron
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si 
    - 
      type: project-generic-image 
      image: chevron-comp1.png
    - 
      type: project-generic-text
      heading: Component Kinematics
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si
    - 
      type: project-generic-image 
      image: chevron-comp3.png
    -
      type: project-divider      
    - 
      type: project-generic-2-col-image
      image1: chevron-comp-pts.gif
      image2: chevron1.gif
    -
      type: project-divider              
    - 
      type: project-generic-text
      heading: Component propagation
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur si
    - 
      type: project-generic-image 
      image: chevron-comp3.png                                  

    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    # - 
    #   type: triad-block
    #   heading: my heading
    #   images:
    #     - myimage1.jpg
    #     - myimage2.jpg
    #     - myimage3.jpg
    #   sub-headings:
    #     - myheading1.jpg
    #     - myheading2.jpg
    #     - myheading3.jpg
    #   descriptions:
    #     - mydecrip1.jpg
    #     - mydescrip2.jpg
    #     - mydescrip3.jpg



