--- 
name: A Forest in the Desert
description: An A-frame based webVR prototype for spatially and chronologically relating and presenting the 2D & 3D content generated over the duration of a large-scale installation art project. 
thumbnail: temple360-thumb.jpg
lazysource: temple360-2-thumb.mp4
wip: false
video: true
featured: true
date: Oct - Dec 2017 //
meta: WebVR / HTC Vive / A-Frame
blocks: 
    - 
      type: project-header
      date: Oct - Dec 2017 //
      heading: A Forest in the Desert
      collaborators: In collaboration with John Faichney.
      tags: Design / 3D Content / WebVR / A-Frame
      link: forest.anastasia.io
      link-text: View Prototype
      description:  A Forest in the Desert is an open source VR prototype for sharing immersive content, which uses the content generated over the design & installation of the 2017 Burning Man Temple. It was built with A-Frame and works in both a web interface and in VR with 3DoF/6DoF controllers. 
    - 
      type: project-generic-image 
      image: 360_img.jpg
    - 
      type: project-generic-text
      heading: Sharing 2D content online is easy
      description: So I’m a serial ‘documenter' ie.  ALWAYS taking photos, videos etc. According to Business Insider, people took an estimated 1.2 trillion digital photos alone in 2017.  Of these, we have approx. 3.2 billion photos/videos being shared each day on social media, a phenomenon that speaks to the relative ease at which traditional user generated content can be shared and consumed.
    - 
      type: project-generic-image 
      image: typeseofcontent2.png
    - 
      type: project-generic-text
      heading: Sharing immersive content online in a meaningful way is challenging
      description:  I worked on an art installation for the greater part of 2017 and found myself amassing content at a rapid pace. This culminated with a month’s worth of 360s that I desperately wanted to share, as they offered the most unadulterated story of the project. After researching into ways to present this online .... need to add more here about challenges
      cta: Learn more about the Temple Art Installation >>>
      link: forest.anastasia.io         
    -
      type: project-divider-line        
    - 
      type: project-generic-text
      heading: Prototype  - A Forest in the Desert
      description:  A Forest in the Desert is a prototype that I designed and developed in response to these challenges. I worked with my partner John Faichney, a full stack developer who built about 40% of the prototype and helped me map out the application architecture. The design/ build for version 1.0 of the prototype took approx 3 months. Check out a demo video below or test out the prototype yourself. Also read on if you're interested in my design process.
      cta: Test out the A-Frame prototype in your browser >>>
      link: forest.anastasia.io       
    - 
      type: project-generic-video 
      video-id: PA_7wFIuhZ0
      video-url: https://www.youtube.com/embed/PA_7wFIuhZ0?rel=0&amp;controls=0   
    -
      type: project-design-goals
      heading: Design Goals
      description:  It's important to lay out dsign goals from the begining. These goals were used as a guide through the whole design process and form the base criteria for evaluation.
      items:
        -
          image: map.png
          sub-heading: Provide a meaningful experience through contextually relating content
        -
          image: choose.png
          sub-heading: Allow users to discover content organically
        -
          image: audience.png
          sub-heading: Make it accessible to the largest audience possible
    -
      type: project-divider-line      
    - 
      type: project-generic-text
      heading: I started by trying to better understand how we experience 2D content VS immersive content.
      # description: There are inherent differences in the ways we experience 2D and 3D content that I wanted to try and pinpoint. 
    - 
      type: project-generic-2-col-image 
      image1: 2d-immersive-01.png
      image2: 2d-immersive-02.png
    - 
      type: project-generic-2-col-image 
      image1: 2d-immersive-03.png
      image2: 2d-immersive-04.png            
    - 
      type: project-generic-text
      heading: I also identified existing interaction and design patterns that supported my design goals
      description: Some text about design patterns   
    - 
      type: project-4-col-image 
      items:
        -
          image: pattern-3Dmenu.png
          heading: Navigation
          description: 3D Menu
        -
          image: pattern-panel.png
          heading: Information
          description: 3D Panels
        -
          image: pattern-teleport.png
          heading: Locomotion
          description:  Teleportation
        -
          image: pattern-marker.png 
          heading: Navigation
          description: Markers                                                    
    - 
      type: project-generic-text
      heading: Establishing a look & feel for the design helped me ensure visual consistency across the experience
      description:  
    - 
      type: project-generic-image 
      image: temple360-visuals.jpg         
    - 
      type: project-3-col-image 
      items:
        -
          image: visuals-architectural.png
          heading: 3D 'architectural' elements
          #description: 3D Menu 
        -
          image: visuals-layering.png
          heading: Contrasting lines / layering
          #description: 3D Menu   
        -
          image: visuals-tones.png
          heading: Natural tones
          # description: 3D Menu           
    - 
      type: project-generic-text
      heading: Defining a typical user flow allowed me to sequence the application and prioritize information
      description:                                                  
    - 
      type: project-generic-text
      heading: Design Goal 1 > Provide a meaningful experience through contextually relating content
      description: The menus serve both a navigational and informational purpose, allowing a user to navigate between scenes and toggle the active model or 360. A similar nested menu UI pattern is used for both the model and 360 menus.      
    - 
      type: project-2-col-mp4
      video1: temple360-menu-clip1.mp4 #vid of model menu
      video2: temple360-menu-clip2.mp4 #vid of 360 menu
      # img-backup1: menu-nested-2.jpg
      # img-backup1: menu-wall-1.jpg      
    -
      type: project-divider       
    - 
      type: project-generic-text
      heading: Design Goal 2 > Allow users to discover content organically
      description: Markers are embedded in the model view and indicate locations where content is available.  In the current build, only 360 content is supported. Future iterations will expand upon the marker component to display different types of content.
    - 
      type: project-generic-image 
      image: 171025_UI-content-marker-00.jpg
      
    - 
      type: project-generic-text
      heading: Design Goal 3 > Make it accessible to the largest audience possible
      description: User input is simple and intended to provide a user with selection control and allow a user to navigate around a scene.  While 3DoF or 6DoF controllers are ideal, the prototype also works with WSAD/arrow controls on the keypad.  A reticle is present when not in VR view.  
      cta: View the project code on Github >>>
      link: github.com/avmakesthings/temple360          
    # - 
    #   type: project-generic-text
    #   heading: Environment Design 
    #   description: The design of the environments aims to capture the ephemeral qualities of light and shadow, dust moving across the landscape, flickering light, soft voices — some of the factors that helped the installation be perceived  as sacred space.  

    # - 
    #   type: project-generic-mp4
    #   video1: temple360-home-vid.mp4 
    - 
      type: project-generic-text
      heading: Usability Testing / Evaluation
      description: Given that this prototype was intended for as broad an audience as possible, I wanted it to be implemented a way that was both a compelling experience in a 2d browser /VR and VR device and controller agnostic (3DoF, 6DoF).  Despite it's early stage (limited functionality issues with browser support and network connectivity) I chose to develop the prototype in A-Frame. 
    - 
      type: project-generic-image 
      image: temple360_home-env-model.png                                      
    - 
      type: project-generic-text
      heading: Next steps
      description: Onboarding, User testing, Adding support for unbuilt UI components, Adding support for 2d content, Voice overs, Multi-user support ... open to feedback and suggestions :)            