--- 
name: A Forest in the Desert
description: An A-frame based webVR prototype for spatially and chronologically relating and presenting the 2D & 3D content generated over the duration of a large-scale installation art project. 
thumbnail: temple360-thumb.jpg
lazysource: temple360-2-thumb.mp4
wip: false
video: true
featured: true
date: Oct - Dec 2017 //
meta: WebVR / HTC Vive / A-Frame
blocks: 
    - 
      type: project-header
      date: Oct - Dec 2017 //
      heading: A Forest in the Desert
      collaborators: In collaboration with John Faichney.
      tags: Design / 3D Content / WebVR / A-Frame
      link: forest.anastasia.io
      link-text: View Prototype
      description:  A forest in the desert is an open source VR prototype that aims to contextually relate the content generated over the design and construction of the 2017 Burning Man Temple. It was designed and built using A-Frame. 
    - 
      type: project-generic-image 
      image: 360_img.jpg
    - 
      type: project-generic-text
      description: In an age of ubiquitous computing and portable electronics, capturing and sharing our experiences has never been easier.  Many platforms exist to facilitate this (e.g. Instagram, Facebook, Flickr), yet presenting this content in a meanful way is still challenging.  
    - 
      type: project-generic-image 
      image: temple360_content-types-invert.png    #diagram of different types of content
    - 
      type: project-generic-text
      description:  This was a problem I encountered when trying to present a years worth of content generated over the course of an intallation art project I worked on in 2017. I looked at different categorization techniques for web and mobile content and found that relating content through contexual information eg.geotagging in Apple photos was a good strategy. I designed and developed this prototype as a way to test these methods with imersive content. 
      cta: Test out the A-frame prototype in your browser >>>
      link: forest.anastasia.io
    - 
      type: project-generic-video 
      video-url: https://www.youtube.com/embed/PA_7wFIuhZ0?rel=0&amp;controls=0   
    - 
      type: project-generic-text
      heading: Implementation
      description: Given that this prototype was intended for as broad an audience as possible, I wanted it to be implemented a way that was both a compelling experience in a 2d browser /VR and VR device and controller agnostic (3DoF, 6DoF).  Despite it's early stage (limited functionality issues with browser support and network connectivity) I chose to develop the prototype in A-Frame. 
      cta: View the project code on Github >>>
      link: github.com/avmakesthings/temple360  
    - 
      type: project-generic-image 
      image: temple360-header.jpg         
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: Design Process
      description: Some text about a design process
    # - 
    #   type: project-generic-image 
    #   image: temple360-assets.png                               
    - 
      type: project-generic-text
      heading: Interaction Design 
      description: The interaction design for the prototype is intentionally simple, borrowing heavily from existing VR interaction design patterns.  Text is minimized for ease of experience, however tooltips will be added in future builds. Contextual content is accessed through content markers.
    # - 
    #   type: project-generic-image 
    #   image: temple360-ui-sketch3.jpg 
    - 
      type: project-generic-image 
      image: temple360-ui-sketch5.jpg                                          
    - 
      type: project-generic-text
      heading: Menus
      description: The menus serve both a navigational and informational purpose, allowing a user to navigate between scenes and toggle the active model or 360. A similar nested menu UI pattern is used for both the model and 360 menus.      
    - 
      type: project-2-col-mp4
      video1: temple360-menu-clip1.mp4 #vid of model menu
      video2: temple360-menu-clip2.mp4 #vid of 360 menu
      # img-backup1: menu-nested-2.jpg
      # img-backup1: menu-wall-1.jpg      
    -
      type: project-divider       
    - 
      type: project-generic-text
      heading: Markers
      description: Markers are embedded in the model view and indicate locations where content is available.  In the current build, only 360 content is supported. Future iterations will expand upon the marker component to display different types of content.
    - 
      type: project-generic-image 
      image: 171025_UI-content-marker-00.jpg
    # - 
    #   type: project-generic-2-col-image 
    #   image1: 171025_UI-content-marker-00.jpg #audio marker
    #   image2: 171025_UI-content-marker-00.jpg #image marker            
    - 
      type: project-generic-text
      heading: Controller input
      description: User input is simple and intended to provide a user with selection control and allow a user to navigate around a scene.  While 3DoF or 6DoF controllers are ideal, the prototype also works with WSAD/arrow controls on the keypad.  A reticle is present when not in VR view.    
    - 
      type: project-generic-text
      heading: Environment Design 
      description: The design of the environments aims to capture the ephemeral qualities of light and shadow, dust moving across the landscape, flickering light, soft voices — some of the factors that helped the installation be perceived  as sacred space.  
    - 
      type: project-generic-image 
      image: temple360_home-env-model.png 
    - 
      type: project-generic-mp4
      video1: temple360-home-vid.mp4                          
    - 
      type: project-generic-text
      heading: Next steps
      description: Onboarding, User testing, Adding support for unbuilt UI components, Adding support for 2d content, Voice overs, Multi-user support ... open to feedback and suggestions :)                             


    # - 
    #   type: project-generic-text
    #   description: 
           
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
