--- 
name: Pplanter Web
description:  Web UI/UX Design & Web Development for a website that explains the Pplanter, a sustainable street toilet prototype
thumbnail: pplanter-web-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: A website for Pplanter
      collaborators: In collaboration with Hyphae Design Lab
      description: Web UI/UX Design & Web Development for a website that explains the Pplanter, a sustainable street toilet prototype.     
    - 
      type: project-generic-image 
      image: pplanter-web-diagram.gif     
    -
      type: project-divider      
    - 
      type: project-generic-text
      heading: A Much Needed Update
      description: The old pplanter website was in need of an upgrade. I'm currently in the process of building this website with jade, less, gulp and bootstrap. The interactive svg was made using the snap library. Main screens are displayed below.
    - 
      type: project-generic-image 
      image: pplanter-web-old.jpg
    -
      type: project-divider       
    -
      type: project-design-goals
      heading: Design Goals
      items:
        -
          image: pplanter-web-dg1.svg
          sub-heading: Concisely explain the Pplanter project
        -
          image: pplanter-web-dg2.svg
          sub-heading: Create some fun interactive web elements
        -
          image: pplanter-web-dg3.svg
          sub-heading: Tell a good story
    -
      type: project-divider-line        
    # - 
    #   type: project-generic-text
    #   heading: A Simple Design
    #   description: section description
    - 
      type: project-generic-image 
      image: pplanter-web-wireframe.jpg
    - 
      type: project-generic-image 
      image: pplanter-web_main.jpg    
    -
      type: project-divider      
    - 
      type: carousel
      id: pw1
      images:
        - pplanter-web-screen1.jpg
        - pplanter-web-screen2.jpg
        - pplanter-web-screen3.jpg
        - pplanter-web-screen4.jpg 
    -
      type: project-divider           
      
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
