--- 
name: Rather Be
description: Web & Mobile UI/UX, Visual Design & Brand Development for Rather Be, an action sports media start-up. 
thumbnail: ratherbe-thumb.jpg
link: www.ratherbe.com
date: September 2015 - October 2016
blocks: 
    - 
      type: project-header
      heading: Rather Be
      collaborators: with the Rather Be team, 1st & 3rd
      description: Web & Mobile UI/UX, Visual Design & Brand Development for Rather Be, an action sports media start-up.
      link: www.ratherbe.com    
    - 
      type: project-generic-image 
      image-bak: ratherbe-layout.jpg 
      image: ratherbe-demo.gif
      video: https://www.youtube.com/watch?v=DjH_RfhHhJU&feature=youtu.be
    - 
      type: project-generic-text
      description: RatherBe is an early stage company that produces, curates & distributes high quality action sports media. I joined the company in late 2015 as lead designer,  to develop a beta launch web platform and iOS app. 
    -
      type: project-divider
    -
      type: project-design-goals
      heading: Design Goals
      items:
        -
          image: ratherbe-question.svg
          sub-heading: Refine and communicate product value proposition
        -
          image: ratherbe-brand.svg
          sub-heading: Establish clear brand identity that resonates with target users
        -
          image: ratherbe-user.svg
          sub-heading: Build an engaged audience
    - 
      type: project-generic-image 
      image: ratherbe-desert.jpg
    -
      type: project-divider
    -
      type: triad-small
      heading: Our Users
      items:
        -
          image: ratherbe-athlete.png
          sub-heading: Athletes
          description: Semi-professional to professional athletes required exposure & easy access to a dedicated fanbase
        -
          image: ratherbe-creator.png
          sub-heading: Content Creators
          description: Professional content creators required exposure, connection to athletes/ fans and a place to showcase their work
        -
          image: ratherbe-enthusiast.png
          sub-heading: Enthusiasts
          description: Enthusiasts required a way to connect to others and well as a place to upload and share their experiences.                     
    -
      type: project-divider
    -
      type: project-generic-text
      heading: Building a lifestyle brand
      description:  I worked closely with a select number of target users and our product/ editorial teams to develop the visual identity for the brand, including logos, typefaces & color, culminating in the production of a master brand style guide (excerpts shown below).
    -
      type: triad
      items:
        -
          image: ratherbe-style01.jpg
        -
          image: ratherbe-style02.jpg
        -
          image: ratherbe-style03.jpg
    -
      type: project-divider
    -
      type: project-generic-text
      heading: User Research
      description: >
        One of the most enjoyable aspects of my work involved connecting with our different user groups to better understand their needs and to test how they used our product. As an avid snowboarder and photographer, I thoroughly enjoyed going out to capture competitions like the Burton US Open and Mavericks, as these events provided great insight into our target audience -- I've included a few of my favourite shots below.
    -
      type: project-divider
    -
      type: carousel
      id: rb1
      images:
        - ratherbe-comp1.jpg
        - ratherbe-comp2.jpg
        - ratherbe-comp3.jpg
    -
      type: project-divider
    -
      type: project-generic-text
      heading:  The design process
      description: |
        After the initial phase of redefning the brand identity, I worked closely with our Head of Product to develop our web and iOS beta trials.
        Key aspects included:
        1. Translating our updated brand identity to products, which involcved an entire website redesign & iOS app design
        2. Ensuring that we were able to test and evaluate the designs in the best possible way
        3. Messaging across different touchpoints
        4. Minimizing friction in user flows
    -
      type: project-divider
    -
      type: project-generic-text
      heading: Low-Fidelity Prototyping
      description:  Like the majority of design projects I've worked on, a lot of my time was spent thinking through aspects of the UI or UX design on paper or whiteboards. This low-fidelity medium enabled rapid communication of thoughts and ideas and was used at every phase of the design process.
    -
      type: project-divider      
    -
      type: project-generic-2-col-image
      image1: ratherbe-sketch1.jpg
      image2: ratherbe-sketch2.jpg
    -
      type: project-divider
    -
      type: project-generic-text
      heading: Refining User Flows
      description:  As lead designer, I was responsible for defining our usability KPI's and testing our userflows for key aspects of the product. My process typically involved outlining a basic flow like onboarding, login, content upload or content consumption and testing our assumptions with users using inVision or Usertesting.com.
    - 
      type: project-generic-image 
      image: ratherbe-userflow.png 
    -
      type: project-divider
    -
      type: project-generic-text
      heading: High Fidelity Prototyping
      description: Hi-fi prototypes were created using Sketch, in combination with Illustrator/ Photoshop for the assets.
    - 
      type: project-generic-image 
      image: ratherbe-hifi1.jpg
    - 
      type: project-generic-image 
      image: ratherbe-hifi3.jpg
    -
      type: project-divider
    -
      type: project-generic-text
      heading: UI Kit Specifications & Web Development
      description:  One of my largest contributions to the company was designing and implementing a UI Kit for our website.  The UI Kit provided detailed specifications & micro interaction design for all standard web components such as cards, buttons, fonts and grid layout. I worked closley with our front-end team to overhaul our web product and ensure consistentcy on different devices.       
    # -
    #   type: project-generic-2-col-image
    #   image1: ratherbe-uikit.png
    #   image2: ratherbe-responsive.gif
    -
      type: project-divider-line
    - 
      type: project-generic-image 
      image: ratherbe-mavericks.jpg
    -
      type: project-divider
    -
      type: project-generic-text
      heading: Final Thoughts
      description:  My time at Rather Be was devoted to finding ways by which design could be used to create a lifelyle brand, build an engaged audience and provide a high-quality user experience. While often challenging, it was an incredibly educational experience and one that has met considerable success. Working with a company who's direction resonated so strongly with my own interests in action sports, also allowed me to more deeply engage with the things I love doing. The company is in the process of acquiring more funding but the future looks promising.   




