--- 
name: BCI & the Built Environment
description: Master of Architecture thesis on using consumer grade Brain Computer Interfacing as an input modality for automated environments.
thumbnail: bci-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: BCI & the Built Environment
      # collaborators: people collaborating
      description: Master of Architecture thesis on using consumer grade Brain Computer Interfacing as an input modality for automated environments.
      # url: www.xyz.com
    - 
      type: project-generic-image 
      image: bci-main.jpg
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: More coming soon ...  


    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    