--- 
name: Musubi House
description: Design, Construction Documentation, Detailing & 3D Modelling for an off-the-grid concrete house, located on 100 acres of pasture land on the Paauilo, Big Island, Hawaii
thumbnail: musubi-thumb.jpg
wip: false
featured: false
date: Jun 2014 - Jun 2015 //
meta: Architectural Design / 3D Modeling
blocks: 
    - 
      type: project-header
      heading: Musubi House
      collaborators: In collaboration with Craig Steely Architecture
      description: Design, Construction Documentation, Detailing & 3D Modelling for an off-the-grid concrete house, located on 100 acres of pasture land on the Paauilo, Big Island, Hawaii
      url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: musubi-render1.jpg
    - 
      type: project-generic-text
      description: I worked with Craig Steely Architcture on the design and construction detailing for the Musubi House - a private residence in Hawaii.  A lot of my focus was on 3D modelling in Rhino and producing whitemodel renders in Vray.  Final renders depicted here were produced outside the office.
    # - 
    #   type: project-generic-image 
    #   image: musubi-site1.jpg
    -
      type: project-divider
    - 
      type: project-generic-2-col-image
      image1: musubi-model1.jpg
      image2: musubi-model2.jpg        
    -
      type: project-divider
    # - 
    #   type: project-generic-text
    #   heading: 3D Modelling & Rendering
    #   description: section description     
    -
      type: project-divider
    -
      type: carousel
      id: mh1
      images:
        - musubi-render2.jpg
        - musubi-white-render.jpg
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: More coming soon ...  



    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
