--- 
name: A Forest in the Desert
description: An A-frame based webVR prototype for spatially and chronologically relating and presenting the 3D models, 360 images, photos and video generated over the design, construction and installation of the 2017 Burning Man temple.
thumbnail: temple360-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: A Forest in the Desert
      collaborators: In collaboration with John Faichney and a little help from David lu.
      description: Design, Content curation, 3D modeling, Application architecture, Web development (A-frame, Three.js)
      # url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: hoku-render2.jpg
    -
      type: project-divider
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    - 
      type: project-generic-image 
      image: hoku-render1.jpg 
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
