--- 
name: Digital Ceramics
description: Research into the synthesis of digital fabrication and slip cast ceramics
thumbnail: ceramics-thumb.gif
blocks: 
    - 
      type: project-header
      heading: Digital Ceramics
      collaborators: -For Prof. Ron Rael.  Part 2 of this work is in collaboration with Bryan Allen
      description: some description
      # url: www.xyz.com
    - 
      type: project-generic-image 
      image: ceramics-main.jpg
    -
      type: project-divider
    - 
      type: project-generic-image 
      image: diatom.png
    -
      type: project-divider              
    - 
      type: project-generic-text
      heading: Part 1 - The Good
      description: section description
    -
      type: project-divider  
    - 
      type: project-generic-image 
      image: ceramics-star-tile1.svg
    - 
      type: project-generic-2-col-image
      image1: ceramics-star-tile1.png
      image2: ceramics-star-agg1.png
    - 
      type: project-generic-2-col-image
      image1: ceramics-star-pic6.jpg
      image2: ceramics-star-lights.gif           
    -
      type: project-divider
    - 
      type: project-generic-image 
      image: ceramics-star-pic4.jpg
    -
      type: project-divider              
    - 
      type: project-generic-2-col-image
      image1: ceramics-star-pic3.jpg
      image2: ceramics-star-pic2.jpg
    -
      type: project-divider  
    - 
      type: project-generic-text
      heading: Installation & Lighting
      description: section description      
    - 
      type: project-generic-image 
      image: ceramics-star-pic1.jpg   
    - 
      type: project-generic-image 
      image: ceramics-berkeley-section.png 
                       
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
    -
      type: project-divider  
    - 
      type: project-generic-text
      heading: Part 2 - The Weird
      description: section description 
    -
      type: project-divider  
    - 
      type: project-generic-2-col-image
      image1: ceramics-bone-render2.jpg
      image2: ceramics-bone-render3.jpg
    -
      type: project-divider  
    - 
      type: project-generic-2-col-image
      image1: ceramics-bone-render4.jpg
      image2: ceramics-bone-render5.jpg      
    -
      type: project-divider  
    - 
      type: project-generic-text
      heading: a section heading
      description: section description                         
    -
      type: project-divider  
    - 
      type: project-generic-image
      image: ceramics-bone-drawings.jpg
    -
      type: project-divider  
    - 
      type: project-generic-2-col-image
      image1: ceramics-bone1.gif
      image2: ceramics-bone2.gif 
    -
      type: project-divider
    - 
      type: project-generic-image 
      image: ceramics-bone-render1.jpg        
    -
      type: project-divider    
    - 
      type: project-generic-text
      heading: a section heading
      description: section description              
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    # - 
    #   type: triad-block
    #   heading: my heading
    #   images:
    #     - myimage1.jpg
    #     - myimage2.jpg
    #     - myimage3.jpg
    #   sub-headings:
    #     - myheading1.jpg
    #     - myheading2.jpg
    #     - myheading3.jpg
    #   descriptions:
    #     - mydecrip1.jpg
    #     - mydescrip2.jpg
    #     - mydescrip3.jpg



