--- 
name: Pplanter Web
description:  Web UI/UX Design & Web Development for a website that explains the Pplanter, a sustainable street toilet prototype
thumbnail: pplanter-web-thumb.jpg
blocks: 
    - 
      type: project-header
      heading: A website for Pplanter
      collaborators: In collaboration with Hyphae Design Lab
      description: Web UI/UX Design & Web Development for a website that explains the Pplanter, a sustainable street toilet prototype.     
    - 
      type: project-generic-image 
      image: pplanter-web-diagram.gif     
    -
      type: project-divider      
    - 
      type: project-generic-text
      heading: A Much Needed Update
      description: The old pplanter website ....
    - 
      type: project-generic-image 
      image: pplanter-web-old.jpg
    -
      type: project-divider       
    -
      type: project-design-goals
      heading: Design Goals
      images:
        - pplanter-web-dg1.svg
        - pplanter-web-dg2.svg
        - pplanter-web-dg3.svg
      sub-headings:
        - Concisely explain the Pplanter project
        - Create some fun interactive web elements
        - Tell a good story
    -
      type: project-divider-line        
    - 
      type: project-generic-text
      heading: A Simple Design
      description: section description
    - 
      type: project-generic-image 
      image: pplanter-web-wireframe.jpg
    - 
      type: project-generic-image 
      image: pplanter-web_main.jpg    
    -
      type: project-divider      
    - 
      type: carousel
      images:
        - pplanter-web-screen1.jpg
        - pplanter-web-screen2.jpg
        - pplanter-web-screen3.jpg
        - pplanter-web-screen4.jpg 
    -
      type: project-divider           
      
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    # - 
    #   type: triad-block
    #   heading: my heading
    #   images:
    #     - myimage1.jpg
    #     - myimage2.jpg
    #     - myimage3.jpg
    #   sub-headings:
    #     - myheading1.jpg
    #     - myheading2.jpg
    #     - myheading3.jpg
    #   descriptions:
    #     - mydecrip1.jpg
    #     - mydescrip2.jpg
    #     - mydescrip3.jpg



