--- 
name: Sonar
description: A VR game for Occulus Rift / HTC Vive that uses hand motion tracking through Leap Motion input. 
thumbnail: logo-animated.gif
wip: false
blocks: 
    - 
      type: project-header
      heading: Sonar VR
      # collaborators: In collaboration with Craig Steely Architecture
      description: A VR game for Occulus Rift / HTC Vive that uses hand motion tracking through Leap Motion input. 
      # url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: Sonar-Demo.jpg
      lazysource: Sonar-Demo.gif
#     -
      type: project-divider
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    - 
      type: project-generic-image 
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: More coming soon ...                
#     # - 
#     #   type: project-generic-2-col-image
#     #   image1: myimage1.jpg
#     #   image2: myimage2.jpg
