--- 
name: Line & Form
description: Graphic art with line and form.
thumbnail: whole-campus-thumb.png
wip: false
featured: false
date: Jan 2011 - Now //
meta: Graphic Art /
blocks: 
    - 
      type: project-header
      heading: Line & Form
    #   collaborators: In collaboration with Craig Steely Architecture
      # description: A series of exploratory works, generated through
    #   url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: Wall-piece.jpg
    - 
      type: project-generic-image 
      image: Gradient_shape_1.png        
    - 
      type: project-generic-image 
      image: Lines_1A.jpg        
    - 
      type: project-generic-image 
      image: whole campus diagram.png           
#     -
#       type: project-divider
#     # - 
#     #   type: project-generic-text
#     #   heading: a section heading
#     #   description: section description
#     - 
#       type: project-generic-image 
#       image: hoku-render1.jpg 
#     -
#       type: project-divider
#     - 
#       type: project-generic-text
#       heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
