--- 
name: Laser Eyes
description: My first experiment with ARKit. 
thumbnail: temple360-thumb.jpg
lazysource: laser-eyes-thumb-optimize.mp4
wip: false
featured: false
video: true
date: Jan 2018 //
meta: ARKit / Unity / iOS
blocks: 
    - 
      type: project-header
      heading: Laser Eyes
    #   collaborators: In collaboration with Craig Steely Architecture
      description: I've been starting to experiment with the ARKit plugin in unity... it's a simple way to build to iOS 
    #   url: www.craigsteely.com
    - 
      type: project-generic-mp4
      video1: laser-eyes-2.mp4
#     -
#       type: project-divider
#     # - 
#     #   type: project-generic-text
#     #   heading: a section heading
#     #   description: section description
#     - 
#       type: project-generic-image 
#       image: hoku-render1.jpg 
#     -
#       type: project-divider
#     - 
#       type: project-generic-text
#       heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
