--- 
name: Magic Carpet
description: Developed for Google for the anchor artwork for their new campus. 
thumbnail: Magic_Carpet_Day-Small.jpg
wip: false
date: Apr - Nov 2018 //
meta: AR / Generative Design / 
video: false
featured: true
sortIndex: 1
blocks: 
    - 
      type: project-header
      heading: Magic Carpet
      collaborators: In collaboration with Marisha Farnsworth & our Magic Carpet team.
      description: Design, Construction Documentation & 3D Modelling for a private residence, sited on the high plateau between Hualalai and Moana Loa, Big Island Hawaii.
      # url: www.craigsteely.com
    - 
      type: project-generic-image 
      image: Magic_Carpet_Day-Small.jpg
    -
      type: project-divider
    # - 
    #   type: project-generic-text
    #   heading: a section heading
    #   description: section description
    - 
      type: project-generic-image 
      image: hoku-render1.jpg 
    -
      type: project-divider
    - 
      type: project-generic-text
      heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
