--- 
name: Augmenting Reality
description: Experiments with AR / MR and Unity
thumbnail: augmenting-reality-thumb.jpg
wip: false
featured: true
sortIndex: 2
date: May 2018 //
meta: Unity / Vuforia / AR
blocks: 
    - 
      type: project-header
      date: May 2018 //
      heading: Augmenting Reality
      tags: Unity / Vuforia / AR
      description: A series of Augmented Reality and Mixed Reality experiements with Unity and Vuforia.  
    - 
      type: project-generic-mp4
      video1: AV_Augmenting-reality.mp4
#     -
#       type: project-divider
#     # - 
#     #   type: project-generic-text
#     #   heading: a section heading
#     #   description: section description
#     - 
#       type: project-generic-image 
#       image: hoku-render1.jpg 
#     -
#       type: project-divider
#     - 
#       type: project-generic-text
#       heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
