--- 
name: VR-OS
description: A spatial operating system interface prototype made with Sketch, Unity & Blender.
thumbnail: test005-500.png
wip: true
featured: true
date: Feb 2018 - Now //
meta: VR / Unity / HTC Vive / UI
# blocks: 
#     - 
#       type: project-header
#       heading: Hokukano House
#       collaborators: In collaboration with Craig Steely Architecture
#       description: Design, Construction Documentation & 3D Modelling for a private residence, sited on the high plateau between Hualalai and Moana Loa, Big Island Hawaii.
#       url: www.craigsteely.com
#     - 
#       type: project-generic-image 
#       image: hoku-render2.jpg
#     -
#       type: project-divider
#     # - 
#     #   type: project-generic-text
#     #   heading: a section heading
#     #   description: section description
#     - 
#       type: project-generic-image 
#       image: hoku-render1.jpg 
#     -
#       type: project-divider
#     - 
#       type: project-generic-text
#       heading: More coming soon ...                
    # - 
    #   type: project-generic-2-col-image
    #   image1: myimage1.jpg
    #   image2: myimage2.jpg
